pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
    // This stops the "Mutation" error by forcing versions to stay put
    components.all {
        if (id.group == "org.jetbrains.kotlin") {
            version { strictly("1.9.22") }
        }
    }
}
rootProject.name = "phone-detective"
include ':app'
