pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
    // This part forces the versions to stay put and stops the "Mutation" error
    components.all {
        if (id.group == "org.jetbrains.kotlin") {
            // Forces all Kotlin internal tools to 1.9.22
            version { strictly("1.9.22") }
        }
    }
}
rootProject.name = "phone-detective"
include ':app'
